---
# Exercise for config server and deployment
- name: Exercise for configuring EC2 server and deployment
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup